spring: 
  profiles:
    active:
    - dev
---
spring:
  profiles:  dev # 开发环境
  application: 
    name: microservicecloud-config-lyp-dev
---
spring: 
  profiles: test	# 测试环境
  application: 
    name: microservicecloud-config-lyp-test
  #请以UTF-8格式保存